name: Scraper Test
on: [push, workflow_dispatch]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Node 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Dependencies
        # You need cheerio to run the test
        run: npm install cheerio-without-node-native

      - name: Run Test Script
        # Make sure test.js is in the root folder of your repo
        run: node test.js
